### ISSUE TITLE
Vehicle Commander QML App needs complete re-write

### ISSUE THREAD

**Issue by csmoore** [Esri/message-simulator-qt#14]
The QML-based Vehicle Commander (VC) app is showing some serious signs of age because QML was quite new when this app was originally developed & has changed quite a bit since then. 

When the QML-based runtime API is released (or at least in Beta), we should consider redoing the VC app with today's modern, more stable version of QML.

This will also help resolve the numerous other issues (#5, #10)

**Comment by garys-esri** [comment]
Retiring Vehicle Commander Qt
