### ISSUE TITLE
QML Debugging does not work with Vehicle Commander QML

### ISSUE THREAD

**Issue by csmoore** [Esri/message-simulator-qt#5]
There is a known issue that when the Vehicle Commander project QML is run in the QML debugger, it does initialize in the correct order and the key properties are null when they are referenced at initialization.

```
Debugging starts
QDeclarativeDebugServer: Waiting for connection on port 64495...
QDeclarativeDebugServer: Connection established
qrc:/Resources/qml/Panels/SpotReport/SpotReportPanel.qml:39: TypeError: Result of expression 'equipmentPanel' [null] is not an object.
qrc:/Resources/qml/PanelContainers/MainMenu.qml:45: TypeError: Result of expression 'mainMenu.stack' [null] is not an object.
(THEN A CASCADE OF QML ERRORS)
```

WORKAROUND: For now, you will need to disable the QML debugger to run the debugger as a workaround (in Projects | Run | Debugger Settings). You will be able to debug C++, just not QML (you'll need to use QML console.log's)

**Comment by garys-esri** [comment]
Retiring Vehicle Commander Qt
